name: CI

on: [push, pull_request]

jobs:
  python:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python: ["3.8", "3.9", "3.10"]

    defaults:
      run:
        shell: ${{ contains(matrix.os, 'windows') && 'powershell' || 'bash -l {0}' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: environment.yml
          extra-specs: |
            python=${{ matrix.python }}

      - name: Install Python extension module (pip)
        run: python -m pip install . -vv

      - name: Test Python API
        run: python -m pytest --doctest-modules tests --pyargs tad_dftd3 --cov=tad_dftd3 -vv

      - run: pip3 install coverage
        shell: bash

      - name: Upload coverage report
        uses: codecov/codecov-action@v1
